### ISSUE TITLE
Cannot open chat message prompt

### ISSUE THREAD

**Issue by nikivdev** [ahmetkca/PolyOllama#2]
<img width="1460" alt="image" src="https://github.com/ahmetkca/PolyOllama/assets/6391776/0d10a114-7790-4ff2-9bd5-481d9e991248">

Have backend and frontend running.

In browser, I activated `cmd+k` but nothing happens.

<img width="1319" alt="image" src="https://github.com/ahmetkca/PolyOllama/assets/6391776/d77810ec-31c8-4f5d-80a6-6db5ef0dc593">

Just get bunch of keyboard events logged.

I am looking to use PolyOllama to run multiple requests to my same model in parallel (from CLI).

How can I do that?

Thank you. ♥️

**Comment by ahmetkca** [comment]
Hi nikita, I believe we resolved this issue on discord, so closing this comment assuming you are not experiencing this anymore since our conversation on discord.
